Translate react conf blog
reactjs/ja.reactjs.org pull request #460
Opened 2021-12-27 05:10 UTC by smikitky

React Conf 2021 記事の翻訳です

今の bot ってコンフリクトがない場合に auto-merge する動作がうまくいってないんですかね…手作業で main に `git merge upstream/main` してあります。

2021-12-29 14:49 UTC, koba04 requested changes
ありがとうございます！いくつかコメントしたので確認お願いします！ 🙏

2021-12-29 14:49 UTC, koba04 commented on content/blog/2021-12-17-react-conf-2021-recap.md
> +React Conf がオンラインで開催されたのは今回が初めてですが、イベントは 8 つの言語に翻訳され、無料でストリーミング配信されました。世界中の参加者が、カンファランス Discord や、すべてのタイムゾーンの方がアクセスしやすいように行われたリプレイイベントに参加しました。登録者数は 50,000 人以上に達し、19 の演題は 60,000 回以上閲覧され、両イベントを通じて Disc
typo

```suggestion
React Conf がオンラインで開催されたのは今回が初めてですが、イベントは 8 つの言語に翻訳され、無料でストリーミング配信されました。世界中の参加者が、カンファレンスの Discord や、すべてのタイムゾーンの方がアクセスしやすいように行われたリプレイイベントに参加しました。登録者数は 50,000 人以上に達し、19 の演題は 60,000 回以上閲覧され、両イベントを通じて Discord には 5,000 人の参加者が集まりました。
```

2021-12-29 14:49 UTC, koba04 commented on content/blog/2021-12-17-react-conf-2021-recap.md
> +## サスペンスを使ったストリーミング付きサーバレンダリング {#streaming-server-rendering-with-suspense}
nits: この後でもストリーミングサーバレンダリングという表現を使っているので、「Streaming Server Rendering」は「ストリーミングサーバレンダリング」と訳すとするでいいのかなと思いましたがいかがでしょうか？

```suggestion
## サスペンスを使ったストリーミングサーバレンダリング {#streaming-server-rendering-with-suspense}
```

2021-12-29 14:49 UTC, koba04 commented on content/blog/2021-12-17-react-conf-2021-recap.md
> +React 18 にはサスペンスを使ったサーバサイドレンダリングの機能の改善が含まれています。
nits: 原文でも SSR のパフォーマンスに対する改善と言っているので、パフォーマンスという言葉を入っていてもいいのかなと思いました。

```suggestion
React 18 にはサスペンスを使ったサーバサイドレンダリングのパフォーマンス改善が含まれています。
```

2021-12-29 14:49 UTC, koba04 commented on content/blog/2021-12-17-react-conf-2021-recap.md
> +## React ワーキンググループの初立ち上げ {#the-first-react-working-group}
nits: 立ち上げるという言葉だけでも `The first` のニュアンスは入っているように感じたので立ち上げだけでもいいのかなと感じました。

```suggestion
## React ワーキンググループの立ち上げ {#the-first-react-working-group}
```

2021-12-29 14:49 UTC, koba04 commented on content/blog/2021-12-17-react-conf-2021-recap.md
> +このリリースにおける新機能をサポートするため、新たに構成された React DevTools チームと、開発者が React サプリをデバッグしやすくするための新たなタイムラインプロファイラについて発表しました。
```suggestion
このリリースにおける新機能をサポートするため、新たに構成された React DevTools チームと、開発者が React アプリをデバッグしやすくするための新たなタイムラインプロファイラについて発表しました。
```

2021-12-29 14:49 UTC, koba04 commented on content/blog/2021-12-17-react-conf-2021-recap.md
> +React の学習や React による設計についての一連の発表は [Rachel Nabors](https://twitter.com/rachelnabors) からスタートしました。その中では React の [新ドキュメント](https://beta.reactjs.org/) に関しての我々の注力に関してのキーノートがありました：
「関しての」が連続していたので調整してみました。

```suggestion
React の学習や React による設計についての一連の発表は [Rachel Nabors](https://twitter.com/rachelnabors) からスタートしました。その中では React の [新ドキュメント](https://beta.reactjs.org/) に対する我々の注力についてのキーノートがありました：
```

2021-12-29 14:49 UTC, koba04 commented on content/blog/2021-12-17-react-conf-2021-recap.md
> +**アクセシビリティ、ツーリング、サーバコンポーネントコミュニティからの発表：**
それぞれのコミュニティがあるような印象を受けたので少し言い換えてみました。

```suggestion
**アクセシビリティ、ツーリング、サーバコンポーネントについてコミュニティからの発表：**
```

2022-01-04 01:28 UTC, smikitky commented on content/blog/2021-12-17-react-conf-2021-recap.md
> +## React ワーキンググループの初立ち上げ {#the-first-react-working-group}
React 19 や 20 のときはまた毎回別個に WG を作るつもりですよ、くらいの意図があるのかなと思っていましたが、まあ「初」だといずれにせよ分かりづらいですね…

2022-01-04 01:32 UTC, merged